---
# This playbook install some basic ubuntu packages

- name: install core packages
  apt: pkg={{item}} state=present
  with_items:
    - git
    - vim
    - tmux
    - curl
    - wget
    - ranger
    - build-essential
    - openssh
    - python-software-properties 
    - python3
    - python-pip
    - g++
    - make
    - libcairo2-dev 
    - libav-tools 
    - nfs-common
    - portmap

# (HACK): Some linux distributions didn't provide a default .bashrc.
- name: ensure $HOME/.bashrc is present
  command: touch /home/{{whoami}}/.bashrc

# (HACK): Do ansible local
- name: install ansible
  sudo: no
  shell: pip install ansible
