---
# Playbook to bake box to a hacker's box

- hosts: vagrant
  become: yes
  vars:
    whoami: vagrant
    accept_hostkey: true
  tasks:
    - include: apt.yml
    - include: base.yml
    - include: vim.yml
    - include: zsh.yml
    - include: python.yml
