---
# This playbook install some goodies for nodejs.

# - name: install node source
#   sudo: yes
#   shell: curl -sL https://deb.nodesource.com/setup_8.x | bash -

# - name: install nodejs
#   apt: pkg={{item}} state=present
#   with_items:
#     - nodejs
    
- name: install nvm
  sudo: no
  shell:  cd /home/{{whoami}} && curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash

- name: Setting env and bashrc
  sudo: no
  lineinfile: dest=/home/{{whoami}}/.bashrc
              line='export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"'
              state=present
              backup=no

- name: Setting env and bashrc
  sudo: no
  lineinfile: dest=/home/{{whoami}}/.bashrc
              line='export NVM_NODEJS_ORG_MIRROR="https://unofficial-builds.nodejs.org/download/release"'
              state=present
              backup=no

- name: Loading nvm
  sudo: no
  shell:
    - source /home/{{whoami}}/.bashrc

- name: setting nvm
  sudo: no
  shell:
    - nvm install node

- name: install node packages
  shell:
    - npm i -g yarn
    - npm i -g serve
